require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/games", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Game. As you add validations to Game, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:game)
  }

  let(:invalid_attributes) {
    {
      name: "BADGAME",
      teams: "WHAT IS THIS?"
    }
  }

  let(:invalid_update_attributes) {
    skip("Add assertions for updated state")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # GamesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {'HTTP_ACCEPT' => "application/json"}
  }

  def user_token(user)
    token = Knock::AuthToken.new(payload: { sub: user.id }).token
    return {
        'HTTP_ACCEPT' => "application/json",
        'Authorization': "Bearer #{token}"
      }
  end

  describe "GET /index" do
    it "renders a successful response" do
      Game.create! valid_attributes
      get api_games_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      game = Game.create! valid_attributes
      get api_game_url(game), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    before(:each) do
      user = FactoryBot.create(:user)
      @token_headers = user_token(user)
      @game = FactoryBot.create(:game)
    end
    context "with valid parameters" do
      it "creates a new Game" do
        expect {
          post api_games_url,
               params: { game: valid_attributes }, headers: @token_headers, as: :json
        }.to change(Game, :count).by(1)
      end

      it "renders a JSON response with the new game" do
        post api_games_url,
             params: { game: valid_attributes }, headers: @token_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Game" do
        expect {
          post api_games_url,
               params: { game: invalid_attributes }, as: :json
        }.to change(Game, :count).by(0)
      end

      it "renders a JSON response with errors for the new game" do
        post api_games_url,
             params: { game: invalid_attributes }, headers: @token_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          started: true
        }
      }

      it "updates the requested game" do
        game = Game.create! valid_attributes
        patch api_game_url(game),
              params: { game: new_attributes }, headers: valid_headers, as: :json
        game.reload
        expect(game.started).to eq(true)
      end

      it "renders a JSON response with the game" do
        game = Game.create! valid_attributes
        patch api_game_url(game),
              params: { game: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq("application/json")
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the game" do
        game = Game.create! valid_attributes
        patch api_game_url(game),
              params: { game: invalid_update_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    before(:each) do
      user = FactoryBot.create(:user)
      @token_headers = user_token(user)
      @game = FactoryBot.create(:game)
    end

    it "destroys the requested game" do
      game = Game.create! valid_attributes
      expect {
        delete api_game_url(game), headers: @token_headers, as: :json
      }.to change(Game, :count).by(-1)
    end
  end
end
