require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/game_sessions", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # GameSession. As you add validations to GameSession, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:game_session)  
  }

  let(:invalid_attributes) {
    {
      player_name: nil
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # Api::GameSessionsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {'HTTP_ACCEPT' => "application/json" }
  }

  describe "GET /index" do
    it "renders a successful response" do
      game_session = FactoryBot.build(:game_session)
      game_session.save
      get api_game_sessions_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      game_session = FactoryBot.build(:game_session)
      game_session.save
      get api_game_session_url(game_session), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      before(:each) do
        game = FactoryBot.create(:game)
        @game_session_attributes = attributes_for(:game_session, game_id: game.id)
      end
      it "creates a new GameSession" do
        expect {
          post api_game_sessions_url,
               params: { game_session: @game_session_attributes }, headers: valid_headers, as: :json
        }.to change(GameSession, :count).by(1)
      end

      it "renders a JSON response with the new api_game_session" do
        post api_game_sessions_url,
             params: { game_session: @game_session_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GameSession" do
        expect {
          post api_game_sessions_url,
               params: { game_session: invalid_attributes }, as: :json
        }.to change(GameSession, :count).by(0)
      end

      it "renders a JSON response with errors for the new api_game_session" do
        post api_game_sessions_url,
             params: { game_session: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    before(:each) do
      @game_session = FactoryBot.build(:game_session)
      @game_session.save
    end

    context "with valid parameters" do
      let(:new_attributes) {
        {
          player_name: "Brilliant"
        }
      }

      it "updates the requested api_game_session" do
        
        patch api_game_session_url(@game_session),
              params: { game_session: new_attributes }, headers: valid_headers, as: :json
        @game_session.reload
        expect(@game_session.player_name).to eq("Brilliant")
      end

      it "renders a JSON response with the api_game_session" do
        patch api_game_session_url(@game_session),
              params: { game_session: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq("application/json")
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the api_game_session" do
        patch api_game_session_url(@game_session),
              params: { game_session: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested api_game_session" do
      game_session = FactoryBot.build(:game_session)
      game_session.save
      expect {
        delete api_game_session_url(game_session), headers: valid_headers, as: :json
      }.to change(GameSession, :count).by(-1)
    end
  end
end
