require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/messages", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Message. As you add validations to Message, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:message, :for_user)
  }

  let(:invalid_attributes) {
    {
      content: nil
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # MessagesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {'HTTP_ACCEPT' => "application/json" }
  }

  def user_token(user)
    token = Knock::AuthToken.new(payload: { sub: user.id }).token
    return {
        'HTTP_ACCEPT' => "application/json",
        'Authorization': "Bearer #{token}"
      }
  end

  describe "GET /index" do
    it "renders a successful response" do
      user = FactoryBot.create(:admin_user)
      token_headers = user_token(user)
      FactoryBot.create(:message, :for_user)
      get api_messages_url, headers: token_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      message = FactoryBot.create(:message, :for_user)
      get api_message_url(message), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    before(:each) do
      chatroom = FactoryBot.create(:chatroom)
      user = FactoryBot.create(:user)
      @message_attributes = {chatroom_id: chatroom.id, speakerable_type: 'User', speakerable_id: user.id, content: 'speak' }
    end
    context "with valid parameters" do
      it "creates a new Message" do

        
        expect {
          post api_messages_url,
               params: { message: @message_attributes }, headers: valid_headers, as: :json
        }.to change(Message, :count).by(1)
      end

      it "renders a JSON response with the new message" do
        post api_messages_url,
             params: { message: @message_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Message" do
        expect {
          post api_messages_url,
               params: { message: invalid_attributes }, as: :json
        }.to change(Message, :count).by(0)
      end

      it "renders a JSON response with errors for the new message" do
        post api_messages_url,
             params: { message: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    before(:each) do
      @user = FactoryBot.create(:user)
      @message = FactoryBot.create(:message, :for_user, speakerable: @user)
      @token_headers = user_token(@user)
    end

    context "with valid parameters" do
      let(:new_attributes) { 
        {
          content: 'I MISSPOKE'
        }
      }

      it "updates the requested message" do
        
        patch api_message_url(@message),
              params: { message: new_attributes }, headers: @token_headers, as: :json
        @message.reload
        expect(@message.content).to eq("I MISSPOKE")
      end

      it "renders a JSON response with the message" do
        
        patch api_message_url(@message),
              params: { message: new_attributes }, headers: @token_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq("application/json")
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the message" do
        
        patch api_message_url(@message),
              params: { message: invalid_attributes }, headers: @token_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested message" do
      user = FactoryBot.create(:user)
      message = FactoryBot.create(:message, :for_user, speakerable: user)
      token_headers = user_token(user)

      expect {
        delete api_message_url(message), headers: token_headers, as: :json
      }.to change(Message, :count).by(-1)
    end
  end
end
