require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/users", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:user)
  }

  let(:invalid_attributes) {
    {
      name: nil
    }
  }

  def admin_token
    admin_user = FactoryBot.create(:admin_user)
    token = Knock::AuthToken.new(payload: { sub: admin_user.id }).token
    return {
        'HTTP_ACCEPT' => "application/json",
        'Authorization': "Bearer #{token}"
      }
    
  end

  def user_token(user)
    token = Knock::AuthToken.new(payload: { sub: user.id }).token
    return {
        'HTTP_ACCEPT' => "application/json",
        'Authorization': "Bearer #{token}"
      }
  end
  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {
      'HTTP_ACCEPT' => "application/json"
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      # User.create! valid_attributes
      user = FactoryBot.create(:user)
      token_headers = user_token(user)
      get api_users_url, headers: token_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      # user = User.create! valid_attributes
      user = FactoryBot.create(:user)
      token_headers = user_token(user)
      get api_user_url(user), headers: token_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new User" do
        expect {
          post api_users_url,
               params: { user: valid_attributes }, headers: valid_headers, as: :json
        }.to change(User, :count).by(1)
      end

      it "renders a JSON response with the new user" do
        post api_users_url,
             params: { user: valid_attributes}, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new User" do
        expect {
          post api_users_url,
               params: { user: invalid_attributes }, as: :json
        }.to change(User, :count).by(0)
      end

      it "renders a JSON response with errors for the new user" do
        post api_users_url,
             params: { user: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to include("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          avatar: "NEW STRING"
        }
      }

      it "updates the requested user" do
        # user = User.create! valid_attributes
        user = FactoryBot.create(:user)
        token_headers = user_token(user)
        patch api_user_url(user),
              params: { user: new_attributes }, headers: token_headers, as: :json
        user.reload
        expect(user.avatar).to eq("NEW STRING")
      end

      it "renders a JSON response with the user" do
        # user = User.create! valid_attributes
        user = FactoryBot.create(:user)
        token_headers = user_token(user)
        patch api_user_url(user),
              params: { user: new_attributes }, headers: token_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to include("application/json")
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the user" do
        # user = User.create! valid_attributes
        user = FactoryBot.create(:user)
        token_headers = user_token(user)
        patch api_user_url(user),
              params: { user: invalid_attributes }, headers: token_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to include("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user" do
      # user = User.create! valid_attributes
      user = FactoryBot.create(:user)
      token_headers = user_token(user)
      expect {
        delete api_user_url(user), headers: token_headers, as: :json
      }.to change(User, :count).by(-1)
    end
  end
end
